import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vocabii",
  description: "Generated by create next app",
  openGraph: {
    title: "Your Open Graph Title",
    description: "Your Open Graph Description",
    images: [
      {
        url: "/logoww.png",
        width: 800,
        height: 600,
        alt: "Description of the image",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no" />
      </head>
      <body className={inter.className}>
        <div className="flex flex-col justify-between w-full min-h-screen">
          <main className="flex-grow w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
